### ISSUE TITLE
is github synced with the latest hyper3dge 2.0.2 changes?

### ISSUE THREAD

**Issue by ryan-sg** [3dfxdev/hyper3DGE#2]
Hi!  I don't know any other place I can ask this, trying to register on the forums doesn't seem to be working for me right now...known issue?

Just wanting to know if this github repo is the main source for hyper3dge or just a mirror that gets occasionally updated? 

I have a copy of master checked out and managed to build it on OpenBSD with some changes, but noticed some issues in my build that are marked as fixed in the 2.0.2 changelog, such as ssg showing in doom1.  typing 'version' in the console of my build says 3DGE v2.0.1, but i'm using edge2.wad, and doom_ddf files from the 2.0.2 release.

cheers, thanks for all your efforts!

**Comment by Brendoe1** [comment]
Try checking out the bump_mapping branch. It seems to have fixes in it that should have been made in the main branch instead, and is generally more up-to-date.

**Comment by TDGMods** [comment]
Ah yes, it was an oversight while I was adjusting to using Git. I'll track
the changes down and commit. The actual console version is something I
forget to update sometimes.

The current experimental branch (but a bit broken) is the bump-mapping
version. I would not recommend using the bump-mapping branch for any
serious gameplay because it's pretty broken.

I will have to re-push the changes I made to the main branch {I will do
that in an hour or two).


 It's up to you if you want to use bump_mapping, but it is full of holes
and issues because of the rendering re-write.

**Comment by ryan-sg** [comment]
hey hey, how about a sync with the 2.0.3 release of hyper3dge? :)

**Comment by TDGMods** [comment]
Done =)
