### ISSUE TITLE
the new -v135 switch

### ISSUE THREAD

**Issue by ryan-sg** [3dfxdev/hyper3DGE#26]
This is more of a suggestion than a problem, but rather than having the engine bomb out telling the user to run it again with the -v135 compatibility option, why not just automatically detect that condition and enable v135 without user intervention?

**Comment by Corbachu** [comment]
It was a deliberate move to force people away from using EDGE 1.35, since that author gets bugged about it enough, and 3DGE is now different enough that the two won't be compatible. The idea here is that the user, modder, whatever -- will be too lazy to run it with a command line switch when they can change the VERSION directives in doom_ddf. Also it is part of our forward-thinking: we don't want to waste time on new mods that might still be using old DDFs that have had numerous bugs fixed/etc. 

It sound like a PITA, but it's necessary to really break away from our predecessor. We have already made it explicit that if users want backward compatibility, 2.0.4 Final or 1.36 Final would be the versions to use.

**Comment by ryan-sg** [comment]
Ah yes that sounds good then.  I actually thought this WAS the spiritual continuation if edge, and Andrew Apted had stopped working on edge?

**Comment by Corbachu** [comment]
This is the direct continuation of EDGE. Andrew helped me and the others grasp the engine and submitted patches for 3DGE bugs for the past 4 years or so, but he's ready to move on. He stopped working on it for a reason ;)

**Comment by ryan-sg** [comment]
Ahh okay, I believe I understand now, sorry for the noise! :-)
