### ISSUE TITLE
Can you compile the latest master commit?

### ISSUE THREAD

**Issue by usernameak** [3dfxdev/hyper3DGE#5]
Or give me libvorbis.a, libvorbisfile.a and libogg.a for Windows because i cannot compile them with MinGW.

**Comment by Corbachu** [comment]
Sure thing! If you go to the sourceforge page, the very early source zips have precompiled libraries, maybe it is 1.36A or 1.36B, which was before we moved to Github (look in the lib_win32 folder, all libs are precompiled), though I do not remember if I have since updated the dependency versions. I also use MinGW, so I can verify that they will indeed work. :)

**Comment by Corbachu** [comment]
Also, it might be a good idea to reclone the repo fresh. Chris (ctd1500) rewrote history and removed the IWAD so just to be sure, do a fresh checkout.

**Comment by Corbachu** [comment]
https://sourceforge.net/projects/edge2/files/3DGE%20SOURCE/3DGE-1.36.3a-Source.7z/download

That is the source package with precompiled libs :)

**Comment by usernameak** [comment]
undefined reference to `bump_map_shader::lightParamAmbient`
and similar errors

**Comment by Corbachu** [comment]
Something might have broken when we removed that IWAD. When my PC gets up and running, I will take a look at it asap.

**Comment by Corbachu** [comment]
I need to merge some stuff from bump_mapping - my main PC completely died, so I will reorganize the main branch tomorrow once I grab a clean copy. I will test an verify before sending to master.

**Comment by Corbachu** [comment]
Wait -- did you do a clean re-clone AK? Also, build with Makefile.xming.

**Comment by usernameak** [comment]
Just recloned. And what difference is between Makefile.xming and Makehard.xming?

**Comment by Corbachu** [comment]
No problem! I can understand you just fine =)

Makehard.xming is for Win32 hard links (absolute paths), while Makefile.xming is relaxed and assumes your paths in MinGW/libs/et all are set up correctly.

Also, I just realized - you will **need to pull the md5_conv library from the bump_mapping branch** and paste it into your master clone. Seems when things had to be redone due to that IWAD some stuff regressed.

**Comment by Corbachu** [comment]
**I just pushed the corrected changes to /master. It should now compile correctly.**

**Comment by usernameak** [comment]
`mkdir -p obj_win32/coal
mkdir -p obj_win32/ddf
mkdir -p obj_win32/deh_edge
mkdir -p obj_win32/edge
mkdir -p obj_win32/md5_conv
mkdir -p obj_win32/md5_conv/kmq2
mkdir -p obj_win32/epi
mkdir -p obj_win32/glbsp
mkdir -p obj_win32/timidity
g++ -O3 -ffast-math -msse2 -mfpmath=sse -fno-strict-aliasing -Wall -I -DWIN32 -Ilib_win32/SDL/include -Ilib_win32/glew-1.5.8/include/GL -Ihawknl/include -Ilib_win32/libpng-1.2.12 -Ilib_win32/jpeg-6b -Ilib_win32/zlib-1.2.3/zlib-1.2.3 -DUSE_OGG -Ilib_win32/libogg-1.3.2/include -Ilib_win32/libvorbis-1.3.5/include -I../ -o obj_win32/md5_conv/md5_draw.o -c md5_conv/md5_draw.cc
md5_conv/md5_draw.cc:29:59: fatal error: C:\hyperedge\Dream3DGE\PC136\md5_conv\GL\glut.h: No such file or directory
 #include <C:\hyperedge\Dream3DGE\PC136\md5_conv\GL\glut.h>
                                                           ^
compilation terminated.
make: *** [obj_win32/md5_conv/md5_draw.o] Error 1
`

**Comment by Corbachu** [comment]
You need to change the include paths to point to your headers and local directory. I could have sworn I changed this. But the recent IWAD fiasco must have reverted to the hard paths.

So, [yourpath]/glut.h, or if you installed it through MinGW, just <glut.h>

Wait until I commit 2.0.4 tonight. All of it has since been fixed and I recently updated a lot of the GL headers (and image libs/etc) to more modern versions (or, if compiling with MakeSIMD, entirely different libraries). I will include the new pre-compiled headers and libs from lib_win32 to my server for easy fetching.

Sorry for the frustration, all of this mess was supposed to have been fixed. Mark my words, when the new code gets commited, I will also include  libs_build.md that will outline specifically what to link to.

**Comment by Corbachu** [comment]
Also, going to redo a lot of the paths in /src, but that will be in a new branch.

**Comment by Corbachu** [comment]
Would I would love to do is have optional Visual Studio support for Windows rather than having to use the Makefile, would also aid in debugging -- alas, I have no experience setting up an existing Make project with it. Maybe some day!

**Comment by usernameak** [comment]
> tonight
What is your timezone?

**Comment by Corbachu** [comment]
I apologize (it is PST here in California), I have been feeling a bit under the weather the last few days. I am a bit better today, so if not tonight then tomorrow I will make the commits.

**Comment by usernameak** [comment]
is there a possible way to set normal map to texture?

**Comment by Corbachu** [comment]
For model textures, yes, but for all others it is being worked on. We have to revamp a lot of the rendering system to allow this, which is ongoing. :-)
