### ISSUE TITLE
Building on Android

### ISSUE THREAD

**Issue by usernameak** [3dfxdev/hyper3DGE#6]
I think that it can be built on Android, but I need makefiles!

**Comment by Corbachu** [comment]
This would be awesome! What kind of makefiles would be needed? I have all of the Droid SDK, but I have never built anything for the platform.

**Comment by Brendoe1** [comment]
I was looking into that too... there's an SDK for porting native c/c++ code
to android, but I have currently no clue in heck how it works and haven't
had time to look into it. I know how to build a makefile, but I'm not sure
what needs to be in it to build on that platform.

**Comment by usernameak** [comment]
> This would be awesome! What kind of makefiles would be needed? I have all of the Droid SDK, but I have never built anything for the platform.
You need Android **N**DK to build native code

**Comment by Corbachu** [comment]
GLEW is already going away with 2.1.0 (the SDL2 update). I will probably let someone else research Android, my time is so thinly spread I cannot afford to focus on anything BUT 3DGE proper. BUT, being an avid Android user myself, I am also intrigued =-P

**Comment by usernameak** [comment]
There's a problem: Android uses OpenGL ES, somehow stripped-down version of OpenGL for small devices :laughing:

**Comment by Brendoe1** [comment]
That doesn't seem so difficult to get around, might affect bump mapping
though... I'll have to look into that.
On May 11, 2016 2:36 AM, "usernameak" <notifications@github.com> wrote:

There's a problem: Android uses OpenGL ES, somehow stripped-down version of
OpenGL for small devices [image: :laughing:]

—
You are receiving this because you commented.

Reply to this email directly or view it on GitHub
<https://github.com/3dfxdev/hyper3DGE/issues/6#issuecomment-218410068>

**Comment by Corbachu** [comment]
Yeah, I am sure the GLES library (whichever one) has calls that wrap around raw GL. I dont think this would be too hard, but I feel we should continue focusing on optimizing the engine first before we branch out into other platforms, especially since there is a known memory leak somewhere in the code.

**Comment by usernameak** [comment]
Bump mapping? No problem. GLSL in GLES is the same as in raw GL.

**Comment by usernameak** [comment]
Memory leak?.. When does it happen?

**Comment by Corbachu** [comment]
We are not sure yet -- without a decent profiler it is hard to track down. It is most noticeable on lesser machines (namely, the Dreamcast). Since I do not use Linux, I cannot use the oft-mentioned Valgrind either :-( 

AK, do you have any ideas on how we can embed a profiler? I think EPI used to have one, a long time ago..

**Comment by usernameak** [comment]
I will install Linux on my PC in a few days, then i will try to profile 3DGE with Valgrind

**Comment by Brendoe1** [comment]
Lol so it turns out valgrind will also build on mac. We should both run it
in case it behaves differently on different platforms.

**Comment by Corbachu** [comment]
Great idea guys! That'll help us all out, also, being able to profile the engine to find out where its weak spots are/eating memory/optimizations-to-be-made. 

I will close this thread -- whoever gets Valgrind working and is able to produce meaningful output should create a new issue with the title: 'Valgrind Report' or something along those lines! 

Great job you two btw! =)
